package cn.xxt.recyclerviewexercise.widgetexercise;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;

import cn.xxt.recyclerviewexercise.R;
/**
 * ListView简单使用
 * @author zhq
 * @date 2017/12/27 上午9:34
 */
public class ListViewTestActivity extends AppCompatActivity implements AdapterView.OnItemSelectedListener, AdapterView.OnItemClickListener{

    private static String[] data = new String[]{
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间",
            "天地逃生",
            "太极",
            "无极",
            "饥饿游戏",
            "荒野求生",
            "绝地大逃杀",
            "乱世佳人",
            "教父",
            "盗梦空间"
    };

    private ListView lvTest;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_list_view_test);

        lvTest = findViewById(R.id.lv_test);
        ArrayAdapter<String> aaData = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, data);
        lvTest.setAdapter(aaData);
        lvTest.setSelection(2);
        lvTest.setOnItemClickListener(this);
        lvTest.setOnItemSelectedListener(this);
    }



    @Override
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        Log.d("itemClick", "click" + position + " item");
    }

    @Override
    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
        Log.d("itemselected", "select" + position + "item");
    }

    @Override
    public void onNothingSelected(AdapterView<?> parent) {
        Log.d("nothingSelected", "nothing selected!");
    }
}
